Add the function of select columns
Interactions-as-a-Service/d1-orm pull request #68
Opened 2023-06-23 17:44 UTC by dannyball710

2023-06-23 17:57 UTC, Skye-31 requested changes
Thanks for the PR!

A minor change to match the SQLite standard would be wonderful. Please also run the `changeset` and `prettify` scripts 🙂

2023-06-23 17:57 UTC, Skye-31 commented on src/queryBuilder.ts
> +				columns = options.columns.map((x) => `\`${String(x)}\``).join(", ");
Can we use `"` (double quotes) for this instead, as is the standard for column names?

2023-06-23 17:57 UTC, Skye-31 commented on test/querybuilder.test.js
> +				expect(statement.query).to.equal("SELECT `id`, `name` FROM `test`");
Likewise

2023-06-23 18:09 UTC, dannyball710 commented
Understood, let me fix it.

2023-06-25 17:55 UTC, Skye-31 commented on src/model.ts
>  	): Promise<InferFromColumns<T> | null> {
One thing I've realised is that when the user is specifying `columns`, the return type of this method is going to be wrong - we'd only want to return the type for the columns which are being returned

There's not any particularly nice way to handle this though 🤔

2024-11-11 21:02 UTC, closed without merging